export const WEEKLY_METRICS = {
  uninsured: "Health Insurance Coverage",
  insured_public: "Public Health Insurance Coverage",
  // todo differentiate ?
  // inc_loss: "",
  // inc_loss_rv: "",
  expect_inc_loss: "Expected Income Loss",
  // payment_not_conf: "",
  rent_not_conf: "Rent Payment Confidence",
  mortgage_not_conf: "Mortgage Payment Confidence",
  rent_caughtup: "Rent Caught Up",
  mortgage_caughtup: "Mortgage Caught Up",
  food_insufficient: "Food Insufficiency",
  spend_savings: "Savings Spending",
  spend_credit: "Credit Card & Loan Spending",
  spend_ui: "Unemployment Insurance Benefit Spending",
  spend_stimulus: "Stimulus Payment Spending",
  // todo: remove?
  // anxious_score: "",
  // worry_score: "",
  // interest_score: "",
  // down_score: "",
  // anxiety_signs: "",
  // depression_signs: "",
  depression_anxiety_signs: "Depression & Anxiety",
  expense_dif: "Household Expenses",
  // not asked for week >= 28
  // telework: "",
  eviction_risk: "Evicton Risk",
  foreclosure_risk: "Foreclosure Risk",
  // not asked for week >= 28
  // learning_fewer: "",
  spend_snap: "SNAP Food Stamp Spending",
} as const;

export const WEEKLY_RACE_VARS = {
  white: "White",
  black: "Black",
  hispanic: "Hispanic",
  other: "Two or more races + Other races",
  asian: "Asian",
  total: "Total",
} as const;

export const WEEKLY_GEOGRAPHIES = {
  US: "United States",
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};

export const WEEK_NUM_MIN = 13;
export const WEEK_NUM_MAX = 63;
